apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: duplicity
    job-name: duplicity-photo-weekly-manual-2bg
    type: photo-weekly
  name: duplicity-photo-weekly-debug
  namespace: duplicity-backup
spec:
  containers:
  - envFrom:
    - secretRef:
        name: aws-api-key
    image: ghcr.io/poggenpower/duplicity-backup:v0.0.0dev12
    imagePullPolicy: Always
    command: ["sleep", "1h"]
    name: duplicity-debug
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 101
      runAsUser: 100
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/mydata
      name: mydata
    - mountPath: /home/app/.ssh
      name: ssh
    - mountPath: /home/app/.gnupg
      name: gnupg
    - mountPath: /home/app/.cache/duplicity
      name: cache
    - mountPath: /opt/backup.yml
      name: config
      subPath: backup.yml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vfth2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: OnFailure
  securityContext:
    fsGroup: 1000
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - name: ssh
    persistentVolumeClaim:
      claimName: duplicity-ssh-photo-weekly
  - name: gnupg
    persistentVolumeClaim:
      claimName: duplicity-gnupg-photo-weekly
  - name: cache
    persistentVolumeClaim:
      claimName: duplicity-cache-photo-weekly
  - name: mydata
    nfs:
      path: /bilder
      server: schapp.wupp
  - configMap:
      defaultMode: 420
      name: duplicity-photo-weekly-f744dghm8t
    name: config
  - name: kube-api-access-vfth2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
