apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -photo-weekly
commonLabels:
  app: duplicity
  type: photo-weekly

configMapGenerator:
- name: duplicity
  behavior: replace
  files:
    - backup.yml=conf/backup.yml 

resources:
- ../base

patches:
- path: ./0400-chron.yaml
  target:
    kind: CronJob



