kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: duplicity-ssh
  namespace: duplicity-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi